name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: install pandoc
      run: sudo apt-get install pandoc

    - name: prepare output dir
      run: 'mkdir html'

    - name: call makefile
      run: |
        ls -l
        make
        ls -l
        cp ./index.html html/
        cp -r ./reveal.js/ html/
        cp -r ./css/ html/

    - name: upload
      uses: actions/upload-artifact@v1
      with:
        name: HTML
        path: html/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master'}}
      with:
        branch: gh-pages
        folder: html

